version: '3.7'
services:
  server:
    image: nextcloud-server
    ports:
      - "12001:80"
    volumes:
      - "server:/var/www/html"
    environment:
      NEXTCLOUD_ADMIN_USER: nextcloud
      NEXTCLOUD_ADMIN_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: db
      NEXTCLOUD_TRUSTED_DOMAINS: "192.168.2.105:12001"
    depends_on:
      - db
    links:
      - db
  db:
    image: nextcloud-db
    ports:
      - "12002:3306"
    volumes:
      - "db:/var/lib/mysql"
volumes:
  server:
  db:
